OPENGL_FUNC(PFNGLCREATEPROGRAMPROC, glCreateProgram);

OPENGL_FUNC(PFNGLGENBUFFERSPROC, glGenBuffers);
OPENGL_FUNC(PFNGLBINDBUFFERPROC, glBindBuffer);
OPENGL_FUNC(PFNGLBUFFERDATAPROC, glBufferData);
OPENGL_FUNC(PFNGLMAPBUFFERRANGEPROC, glMapBufferRange);
OPENGL_FUNC(PFNGLDELETEBUFFERSPROC, glDeleteBuffers);
OPENGL_FUNC(PFNGLGETBUFFERPARAMETERIVPROC, glGetBufferParameteriv);
OPENGL_FUNC(PFNGLUNMAPBUFFERPROC, glUnmapBuffer);
OPENGL_FUNC(PFNGLBINDBUFFERBASEPROC, glBindBufferBase);

//OPENGL_FUNC(PFNGLGETINTEGERVPROC, glGetIntegerv);

OPENGL_FUNC(PFNGLGENFRAMEBUFFERSPROC, glGenFramebuffers);
OPENGL_FUNC(PFNGLBINDFRAMEBUFFERPROC, glBindFramebuffer);
OPENGL_FUNC(PFNGLFRAMEBUFFERTEXTURE2DPROC, glFramebufferTexture2D);
OPENGL_FUNC(PFNGLBLITFRAMEBUFFERPROC, glBlitFramebuffer);
OPENGL_FUNC(PFNGLPROGRAMUNIFORM1FVPROC, glProgramUniform1fv);
OPENGL_FUNC(PFNGLPROGRAMUNIFORM2FVPROC, glProgramUniform2fv);
OPENGL_FUNC(PFNGLPROGRAMUNIFORM3FVPROC, glProgramUniform3fv);
OPENGL_FUNC(PFNGLPROGRAMUNIFORM4FVPROC, glProgramUniform4fv);
OPENGL_FUNC(PFNGLPROGRAMUNIFORM1IVPROC, glProgramUniform1iv);
OPENGL_FUNC(PFNGLPROGRAMUNIFORM2IVPROC, glProgramUniform2ifv);
OPENGL_FUNC(PFNGLPROGRAMUNIFORM3IVPROC, glProgramUniform3iv);
OPENGL_FUNC(PFNGLPROGRAMUNIFORM4IVPROC, glProgramUniform4iv);
OPENGL_FUNC(PFNGLPROGRAMUNIFORMMATRIX2FVPROC, glProgramUniformMatrix2fv);
OPENGL_FUNC(PFNGLPROGRAMUNIFORMMATRIX3FVPROC, glProgramUniformMatrix3fv);
OPENGL_FUNC(PFNGLPROGRAMUNIFORMMATRIX4FVPROC, glProgramUniformMatrix4fv);
OPENGL_FUNC(PFNGLPROGRAMUNIFORM2IVPROC, glProgramUniform2iv);
OPENGL_FUNC(PFNGLPROGRAMUNIFORM1UIVPROC, glProgramUniform1uiv);
OPENGL_FUNC(PFNGLPROGRAMUNIFORM2UIVPROC, glProgramUniform2uiv);
OPENGL_FUNC(PFNGLPROGRAMUNIFORM3UIVPROC, glProgramUniform3uiv);
OPENGL_FUNC(PFNGLPROGRAMUNIFORM4UIVPROC, glProgramUniform4uiv);

OPENGL_FUNC(PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer);
OPENGL_FUNC(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray);
OPENGL_FUNC(PFNGLACTIVETEXTUREPROC, glActiveTexture);
//OPENGL_FUNC(PFNGLBINDTEXTUREPROC, glBindTexture);
OPENGL_FUNC(PFNGLBINDIMAGETEXTUREPROC, glBindImageTexture);

OPENGL_FUNC(PFNGLGENSAMPLERSPROC, glGenSamplers);
OPENGL_FUNC(PFNGLDELETESAMPLERSPROC, glDeleteSamplers);
OPENGL_FUNC(PFNGLSAMPLERPARAMETERIPROC, glSamplerParameteri);

OPENGL_FUNC(PFNGLBINDSAMPLERPROC, glBindSampler);
OPENGL_FUNC(PFNGLPROGRAMUNIFORM1IPROC, glProgramUniform1i);

//OPENGL_FUNC(PFNGLGENTEXTURESPROC, glGenTextures);
//OPENGL_FUNC(PFNGLDELETETEXTURESPROC, glDeleteTextures);
OPENGL_FUNC(PFNGLTEXSTORAGE2DPROC, glTexStorage2D);
//OPENGL_FUNC(PFNGLTEXSUBIMAGE2DPROC, glTexSubImage2D);

OPENGL_FUNC(PFNGLTEXSTORAGE3DPROC, glTexStorage3D);
OPENGL_FUNC(PFNGLTEXSUBIMAGE3DPROC, glTexSubImage3D);

//OPENGL_FUNC(PFNGLCLEARPROC, glClear);
//OPENGL_FUNC(PFNGLCLEARCOLORPROC, glClearColor);
OPENGL_FUNC(PFNGLCLEARDEPTHFPROC, glClearDepthf);
//OPENGL_FUNC(PFNGLCLEARSTENCILPROC, glClearStencil);

OPENGL_FUNC(PFNGLCREATESHADERPROGRAMVPROC, glCreateShaderProgramv);
OPENGL_FUNC(PFNGLGETPROGRAMIVPROC, glGetProgramiv);
OPENGL_FUNC(PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog);
OPENGL_FUNC(PFNGLDELETEPROGRAMPROC, glDeleteProgram);
OPENGL_FUNC(PFNGLDISPATCHCOMPUTEPROC, glDispatchCompute);
OPENGL_FUNC(PFNGLUSEPROGRAMPROC, glUseProgram);

OPENGL_FUNC(PFNGLGENPROGRAMPIPELINESPROC, glGenProgramPipelines);
OPENGL_FUNC(PFNGLUSEPROGRAMSTAGESPROC, glUseProgramStages);
OPENGL_FUNC(PFNGLVALIDATEPROGRAMPIPELINEPROC, glValidateProgramPipeline);
OPENGL_FUNC(PFNGLGETPROGRAMPIPELINEIVPROC, glGetProgramPipelineiv);
OPENGL_FUNC(PFNGLGETPROGRAMPIPELINEINFOLOGPROC, glGetProgramPipelineInfoLog);
OPENGL_FUNC(PFNGLDELETEPROGRAMPIPELINESPROC, glDeleteProgramPipelines);

//OPENGL_FUNC(PFNGLGETERRORPROC, glGetError);
OPENGL_FUNC(PFNGLBINDPROGRAMPIPELINEPROC, glBindProgramPipeline);
//OPENGL_FUNC(PFNGLENABLEPROC, glEnable);
//OPENGL_FUNC(PFNGLDISABLEPROC, glDisable);
//OPENGL_FUNC(PFNGLDRAWARRAYSPROC, glDrawArrays);
//OPENGL_FUNC(PFNGLDRAWELEMENTSPROC, glDrawElements);
